In [79]:
%run chapter\ 1.ipynb
%run chapter\ 2.ipynb
%run chapter\ 3.ipynb

def translation(x,y,z):
    """
    >>> tr = translation(5,-3,2)
    >>> p = point(-3,4,5)
    >>> matrix_multiply(tr, p) == point(2,1,7)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> tr = translation(5,-3,2)
    >>> inv = inverse(tr)
    >>> p = point(-3,4,5)
    >>> matrix_multiply(inv, p) == point(-8,7,3)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> tr = translation(5,-3,2)
    >>> v = vector(-3,4,5)
    >>> matrix_multiply(tr, v) == v
    array([[ True],
           [ True],
           [ True],
           [ True]])

    """
    tr = matrix4x4identity()
    tr[0][3] = x
    tr[1][3] = y
    tr[2][3] = z
    return tr

def scaling(x,y,z):
    """
    >>> tr = scaling(2,3,4)
    >>> p = point(-4,6,8)
    >>> matrix_multiply(tr, p) == point(-8,18,32)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> tr = scaling(2,3,4)
    >>> v = vector(-4,6,8)
    >>> matrix_multiply(tr, v) == vector(-8,18,32)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> tr = scaling(2,3,4)
    >>> inv = inverse(tr)
    >>> v = vector(-4,6,8)
    >>> matrix_multiply(inv, v) == vector(-2,2,2)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> tr = scaling(-1,1,1)
    >>> p = point(2,3,4)
    >>> matrix_multiply(tr, p) == point(-2,3,4)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    """
    return matrix(x,0,0,0, 0,y,0,0, 0,0,z,0, 0,0,0,1)

def rotation_x(rad):
    """
    >>> p = point(0,1,0)
    >>> half_q = rotation_x(np.pi / 4)
    >>> full_q = rotation_x(np.pi / 2)
    >>> np.isclose(matrix_multiply(half_q, p), point(0, np.sqrt(2)/2, np.sqrt(2)/2))
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> np.isclose(matrix_multiply(full_q, p), point(0, 0, 1))
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> p = point(0,1,0)
    >>> half_q = rotation_x(np.pi / 4)
    >>> inv = inverse(half_q)
    >>> np.isclose(matrix_multiply(inv, p), point(0, np.sqrt(2)/2, -np.sqrt(2)/2))
    array([[ True],
           [ True],
           [ True],
           [ True]])
    """
    return matrix(1,0,0,0, 0,np.cos(rad),-np.sin(rad),0, 0,np.sin(rad),np.cos(rad),0, 0,0,0,1)

def rotation_y(rad):
    """
    >>> p = point(0,0,1)
    >>> half_q = rotation_y(np.pi / 4)
    >>> full_q = rotation_y(np.pi / 2)
    >>> np.isclose(matrix_multiply(half_q, p), point(np.sqrt(2)/2, 0, np.sqrt(2)/2))
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> np.isclose(matrix_multiply(full_q, p), point(1, 0, 0))
    array([[ True],
           [ True],
           [ True],
           [ True]])

    """
    return matrix(np.cos(rad),0,np.sin(rad),0, 0,1,0,0, -np.sin(rad),0,np.cos(rad),0, 0,0,0,1)

def rotation_z(rad):
    """
    >>> p = point(0,1,0)
    >>> half_q = rotation_z(np.pi / 4)
    >>> full_q = rotation_z(np.pi / 2)
    >>> np.isclose(matrix_multiply(half_q, p), point(-np.sqrt(2)/2, np.sqrt(2)/2, 0))
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> np.isclose(matrix_multiply(full_q, p), point(-1, 0, 0))
    array([[ True],
           [ True],
           [ True],
           [ True]])

    """
    return matrix(np.cos(rad),-np.sin(rad),0,0, np.sin(rad),np.cos(rad),0,0, 0,0,1,0, 0,0,0,1)

def shearing(xy, xz, yx, yz, zx, zy):
    """
    >>> tr = shearing(1,0,0,0,0,0)
    >>> p = point(2,3,4)
    >>> matrix_multiply(tr, p) == point(5,3,4)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> tr = shearing(0,1,0,0,0,0)
    >>> p = point(2,3,4)
    >>> matrix_multiply(tr, p) == point(6,3,4)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> tr = shearing(0,0,1,0,0,0)
    >>> p = point(2,3,4)
    >>> matrix_multiply(tr, p) == point(2,5,4)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> tr = shearing(0,0,0,1,0,0)
    >>> p = point(2,3,4)
    >>> matrix_multiply(tr, p) == point(2,7,4)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> tr = shearing(0,0,0,0,1,0)
    >>> p = point(2,3,4)
    >>> matrix_multiply(tr, p) == point(2,3,6)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> tr = shearing(0,0,0,0,0,1)
    >>> p = point(2,3,4)
    >>> matrix_multiply(tr, p) == point(2,3,7)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    """
    return matrix(1,xy,xz,0, yx,1,yz,0, zx,zy,1,0, 0,0,0,1)

def dummy_4():
    """
    >>> p1 = point(1,0,1)
    >>> A = rotation_x(np.pi/2)
    >>> B = scaling(5,5,5)
    >>> C = translation(10,5,7)
    >>> p2 = matrix_multiply(A,p1)

    >>> np.isclose(p2,point(1,-1,0))
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> p3 = matrix_multiply(B,p2)
    >>> np.isclose(p3,point(5,-5,0))
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> p4 = matrix_multiply(C,p3)
    >>> p4 == point(15,0,7)
    array([[ True],
           [ True],
           [ True],
           [ True]])

    >>> T = matrix_multiply(matrix_multiply(C,B),A)
    >>> matrix_multiply(T,p1) == p4
    array([[ True],
           [ True],
           [ True],
           [ True]])

    """
    pass

In [80]:
import doctest
doctest.testmod()

TestResults(failed=0, attempted=239)