In [1]:
import numpy as np

def point_or_vector(x, y, z, w):
    """
    Return a tuple represented by a numpy array
    w should be 0.0 (for a vector) or 1.0 (for a point)
 
    >>> point_or_vector(1.0, 2.0, 3.0, 1.0)
    array([1., 2., 3., 1.])

    >>> point_or_vector(1.0, 2.0, 3.0, 0.0)
    array([1., 2., 3., 0.])

    Adding two tuples:
    >>> a1 = point_or_vector(3, -2, 5, 1)
    >>> a2 = point_or_vector(-2, 3, 1, 0)
    >>> a1 + a2 == point_or_vector(1,1,6,1)
    array([ True,  True,  True,  True])

    Negating a tuple:
    >>> a = point_or_vector(1, -2, 3, -4)
    >>> -a == point_or_vector(-1, 2, -3, 4)
    array([ True,  True,  True,  True])
    
    Multiply a tuple by a scalar:
    >>> a = point_or_vector(1, -2, 3, -4)
    >>> a * 3.5 == point_or_vector(3.5, -7, 10.5, -14)
    array([ True,  True,  True,  True])

    Multiply a tuple by a fraction:
    >>> a = point_or_vector(1, -2, 3, -4)
    >>> a * 0.5 == point_or_vector(0.5, -1, 1.5, -2)
    array([ True,  True,  True,  True])

    Dividing a tuple by a scalar:
    >>> a = point_or_vector(1, -2, 3, -4)
    >>> a / 2 == point_or_vector(0.5, -1, 1.5, -2)
    array([ True,  True,  True,  True])
    """
    return np.array([x,y,z,w], dtype=np.float64)

def point(x, y, z):
    """
    >>> point(4, -4, 3)
    array([ 4., -4.,  3.,  1.])

    >>> point_or_vector(1.0, 2.0, 3.0, 1.0) == point(1.0, 2.0, 3.0)
    array([ True,  True,  True,  True])

    >>> point_or_vector(1.0, 2.0, 3.0, 0.0) == point(1.0, 2.0, 3.0)
    array([ True,  True,  True, False])

    """
    return point_or_vector(x,y,z,1.0)

def vector(x, y, z):
    """
    >>> vector(4, -4, 3)
    array([ 4., -4.,  3.,  0.])

    >>> point_or_vector(1.0, 2.0, 3.0, 1.0) == vector(1.0, 2.0, 3.0)
    array([ True,  True,  True, False])

    >>> point_or_vector(1.0, 2.0, 3.0, 0.0) == vector(1.0, 2.0, 3.0)
    array([ True,  True,  True,  True])
    
    Subtracting two vectors:
    >>> v1 = vector(3,2,1)
    >>> v2 = vector(5,6,7)
    >>> v1 - v2 == vector(-2,-4,-6)
    array([ True,  True,  True,  True])

    Subtracting a vector from the zero vector:
    >>> zero = vector(0,0,0)
    >>> v = vector(1,-2,3)
    >>> zero - v == vector(-1, 2, -3)
    array([ True,  True,  True,  True])
    """
    return point_or_vector(x,y,z,0.0)

def magnitude(v):
    """
    >>> v = vector(1,0,0)
    >>> magnitude(v) == 1
    True
    >>> v = vector(0,1,0)
    >>> magnitude(v) == 1
    True
    >>> v = vector(0,0,1)
    >>> magnitude(v) == 1
    True
    >>> v = vector(1,2,3)
    >>> magnitude(v) == np.sqrt(14)
    True
    >>> v = vector(-1,-2,-3)
    >>> magnitude(v) == np.sqrt(14)
    True
    >>> p = point(1,2,3)
    >>> magnitude(p)
    Traceback (most recent call last):
    ...
    ValueError: Only use this function with vectors.
    >>> t = point_or_vector(1,2,3,-2)
    >>> magnitude(p)
    Traceback (most recent call last):
    ...
    ValueError: Only use this function with vectors.
    >>> t = np.array([1,2,3,0,1,2,3,4])
    >>> magnitude(p)
    Traceback (most recent call last):
    ...
    ValueError: Only use this function with vectors.
    """
    if len(v) != 4 or v[3] != 0.0:
        raise ValueError("Only use this function with vectors.")
    return np.sqrt(np.sum(np.square(v)))

def normalize(v):
    """
    >>> v = vector(4,0,0)
    >>> normalize(v) == vector(1,0,0)
    array([ True,  True,  True,  True])

    >>> v = vector(1,2,3)
    >>> sq = np.sqrt(1+4+9)
    >>> normalize(v) == vector(1/sq, 2/sq, 3/sq)
    array([ True,  True,  True,  True])
    """

    return v / magnitude(v)

# try np.vdot(a,b)
def dot(a, b):
    """
    >>> v1 = vector(3, 6, 9)
    >>> v2 = vector(2, 3, 4)
    >>> dot(v1, v2) == 3 * 2 + 6 * 3 + 9 * 4
    True
    """
    return np.sum(a * b)

# try np.inner(a,b)
def cross(a, b):
    """
    >>> v1 = vector(1,2,3)
    >>> v2 = vector(2,3,4)
    >>> cross(v1, v2) == vector(-1,2,-1)
    array([ True,  True,  True,  True])
    >>> v1 = vector(1,2,3)
    >>> v2 = vector(2,3,4)
    >>> cross(v2, v1) == vector(1,-2,1)
    array([ True,  True,  True,  True])
    """
    return vector(a[1] * b[2] - a[2] * b[1],
                 a[2] * b[0] - a[0] * b[2],
                 a[0] * b[1] - a[1] * b[0])

def dummy_1():
    """
    Subtracting two points:
    >>> p1 = point(3,2,1)
    >>> p2 = point(5,6,7)
    >>> p1 - p2 == vector(-2,-4,-6)
    array([ True,  True,  True,  True])
    
    Subtracting a vector from a point:
    >>> p = point(3,2,1)
    >>> v = vector(5,6,7)
    >>> p - v == point(-2,-4,-6)
    array([ True,  True,  True,  True])

    Magnitude of a normalized vector:
    >>> v = vector(1,2,3)
    >>> norm = normalize(v)
    >>> magnitude(norm) == 1
    True
    """
    pass

In [2]:
import doctest
doctest.testmod()

TestResults(failed=0, attempted=64)